//
//  FirebaseKeyGenerator.swift
//  WildWest
//
//  Created by Hugues Stephano Telolahy on 26/04/2020.
//  Copyright © 2020 creativeGames. All rights reserved.
//

import Firebase

class FirebaseKeyGenerator: KeyGeneratorProtocol {
    
    func autoId() -> String {
        guard let key = Database.database().reference().childByAutoId().key else {
            fatalError("Cannot get autogenerated unique identifier")
        }
        
        return key
    }
}
